apiVersion: v1
kind: Service
metadata:
  name: db-backup
  namespace: db-backup
  labels:
    app.kubernetes.io/name: db-backup
    app.kubernetes.io/component: server
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
spec:
  type: ClusterIP
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
    - name: metrics
      port: 9090
      targetPort: metrics
      protocol: TCP
  selector:
    app.kubernetes.io/name: db-backup
    app.kubernetes.io/component: server

---
apiVersion: v1
kind: Service
metadata:
  name: db-backup-headless
  namespace: db-backup
  labels:
    app.kubernetes.io/name: db-backup
    app.kubernetes.io/component: server
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: db-backup
    app.kubernetes.io/component: server

---
apiVersion: v1
kind: Service
metadata:
  name: db-backup-external
  namespace: db-backup
  labels:
    app.kubernetes.io/name: db-backup
    app.kubernetes.io/component: server
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "external"
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
spec:
  type: LoadBalancer
  ports:
    - name: https
      port: 443
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: db-backup
    app.kubernetes.io/component: server
