//go:build graphql

// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package resolvers

import (
	"bytes"
	"fmt"
	"io"
	"strconv"

	"github.com/sanskarpan/db-backup/internal/api/graphql/scalar"
	"github.com/sanskarpan/db-backup/internal/database"
	"github.com/sanskarpan/db-backup/internal/types"
)

type AddDatabaseInput struct {
	Name     string                `json:"name"`
	Type     database.DatabaseType `json:"type"`
	Host     string                `json:"host"`
	Port     int                   `json:"port"`
	Username string                `json:"username"`
	Password string                `json:"password"`
	Database *string               `json:"database,omitempty"`
	SslMode  *SSLMode              `json:"sslMode,omitempty"`
	Tags     []string              `json:"tags,omitempty"`
}

type AddStorageProviderInput struct {
	Name      string      `json:"name"`
	Type      StorageType `json:"type"`
	Config    scalar.JSON `json:"config"`
	IsDefault *bool       `json:"isDefault,omitempty"`
}

type AuditLog struct {
	ID         string          `json:"id"`
	Action     AuditAction     `json:"action"`
	EntityType string          `json:"entityType"`
	EntityID   string          `json:"entityId"`
	User       *User           `json:"user"`
	Changes    scalar.JSON     `json:"changes,omitempty"`
	Metadata   scalar.JSON     `json:"metadata,omitempty"`
	Timestamp  scalar.DateTime `json:"timestamp"`
	IPAddress  *string         `json:"ipAddress,omitempty"`
	UserAgent  *string         `json:"userAgent,omitempty"`
}

type BackupMetadataInput struct {
	Name *string  `json:"name,omitempty"`
	Tags []string `json:"tags,omitempty"`
}

type BackupSort struct {
	Field     BackupSortField `json:"field"`
	Direction SortDirection   `json:"direction"`
}

type BackupStatistics struct {
	TotalBackups    int                 `json:"totalBackups"`
	TotalSize       scalar.ByteSize     `json:"totalSize"`
	AverageSize     scalar.ByteSize     `json:"averageSize"`
	SuccessRate     float64             `json:"successRate"`
	FailureRate     float64             `json:"failureRate"`
	AverageDuration scalar.Duration     `json:"averageDuration"`
	BackupsByType   []BackupTypeCount   `json:"backupsByType"`
	BackupsByStatus []BackupStatusCount `json:"backupsByStatus"`
	BackupTrend     []TrendDataPoint    `json:"backupTrend"`
}

type BackupStatusCount struct {
	Status database.BackupStatus `json:"status"`
	Count  int                   `json:"count"`
}

type BackupTypeCount struct {
	Type      BackupType      `json:"type"`
	Count     int             `json:"count"`
	TotalSize scalar.ByteSize `json:"totalSize"`
}

type BulkOperationResult struct {
	SuccessCount int     `json:"successCount"`
	FailureCount int     `json:"failureCount"`
	Errors       []Error `json:"errors,omitempty"`
}

type ChangePasswordInput struct {
	CurrentPassword string `json:"currentPassword"`
	NewPassword     string `json:"newPassword"`
}

type Checksum struct {
	Algorithm string `json:"algorithm"`
	Value     string `json:"value"`
}

type CreateRetentionPolicyInput struct {
	Name        string `json:"name"`
	KeepLast    *int   `json:"keepLast,omitempty"`
	KeepDaily   *int   `json:"keepDaily,omitempty"`
	KeepWeekly  *int   `json:"keepWeekly,omitempty"`
	KeepMonthly *int   `json:"keepMonthly,omitempty"`
	KeepYearly  *int   `json:"keepYearly,omitempty"`
	MinBackups  *int   `json:"minBackups,omitempty"`
	MaxBackups  *int   `json:"maxBackups,omitempty"`
}

type CreateTeamInput struct {
	Name        string  `json:"name"`
	Description *string `json:"description,omitempty"`
}

type EncryptionInfo struct {
	Enabled   bool    `json:"enabled"`
	Algorithm *string `json:"algorithm,omitempty"`
	KeyID     *string `json:"keyId,omitempty"`
}

type Error struct {
	Message    string      `json:"message"`
	Path       []string    `json:"path,omitempty"`
	Extensions scalar.JSON `json:"extensions,omitempty"`
}

type Metric struct {
	Name      string          `json:"name"`
	Value     float64         `json:"value"`
	Unit      string          `json:"unit"`
	Timestamp scalar.DateTime `json:"timestamp"`
	Labels    scalar.JSON     `json:"labels,omitempty"`
}

type Mutation struct {
}

type NotificationConnection struct {
	Edges       []NotificationEdge `json:"edges"`
	PageInfo    *PageInfo          `json:"pageInfo"`
	TotalCount  int                `json:"totalCount"`
	UnreadCount int                `json:"unreadCount"`
}

type NotificationEdge struct {
	Node   *Notification `json:"node"`
	Cursor string        `json:"cursor"`
}

type NotificationFilter struct {
	Types  []NotificationType  `json:"types,omitempty"`
	Levels []NotificationLevel `json:"levels,omitempty"`
	Read   *bool               `json:"read,omitempty"`
}

type NotificationPayload struct {
	Notification *Notification `json:"notification,omitempty"`
	Errors       []Error       `json:"errors,omitempty"`
}

type NotificationPreferences struct {
	Email             bool    `json:"email"`
	Push              bool    `json:"push"`
	Slack             bool    `json:"slack"`
	QuietHoursEnabled bool    `json:"quietHoursEnabled"`
	QuietHoursStart   *string `json:"quietHoursStart,omitempty"`
	QuietHoursEnd     *string `json:"quietHoursEnd,omitempty"`
}

type NotificationPreferencesInput struct {
	Email             *bool   `json:"email,omitempty"`
	Push              *bool   `json:"push,omitempty"`
	Slack             *bool   `json:"slack,omitempty"`
	QuietHoursEnabled *bool   `json:"quietHoursEnabled,omitempty"`
	QuietHoursStart   *string `json:"quietHoursStart,omitempty"`
	QuietHoursEnd     *string `json:"quietHoursEnd,omitempty"`
}

type Query struct {
}

type RestoreOptions struct {
	ValidateBackup bool     `json:"validateBackup"`
	DropExisting   bool     `json:"dropExisting"`
	Parallel       int      `json:"parallel"`
	Tables         []string `json:"tables,omitempty"`
	ExcludeTables  []string `json:"excludeTables,omitempty"`
}

type RestoreSort struct {
	Field     RestoreSortField `json:"field"`
	Direction SortDirection    `json:"direction"`
}

type RetentionPolicy struct {
	ID          string          `json:"id"`
	Name        string          `json:"name"`
	KeepLast    *int            `json:"keepLast,omitempty"`
	KeepDaily   *int            `json:"keepDaily,omitempty"`
	KeepWeekly  *int            `json:"keepWeekly,omitempty"`
	KeepMonthly *int            `json:"keepMonthly,omitempty"`
	KeepYearly  *int            `json:"keepYearly,omitempty"`
	MinBackups  *int            `json:"minBackups,omitempty"`
	MaxBackups  *int            `json:"maxBackups,omitempty"`
	Rules       []RetentionRule `json:"rules"`
	CreatedAt   scalar.DateTime `json:"createdAt"`
	UpdatedAt   scalar.DateTime `json:"updatedAt"`
}

type RetentionPolicyPayload struct {
	RetentionPolicy *RetentionPolicy `json:"retentionPolicy,omitempty"`
	Errors          []Error          `json:"errors,omitempty"`
}

type RetentionRule struct {
	Type  RetentionRuleType `json:"type"`
	Value int               `json:"value"`
	Unit  TimeUnit          `json:"unit"`
}

type ScheduleOptions struct {
	Compression     types.CompressionType `json:"compression"`
	Encryption      bool                  `json:"encryption"`
	Parallel        int                   `json:"parallel"`
	Tags            []string              `json:"tags"`
	NotifyOnSuccess bool                  `json:"notifyOnSuccess"`
	NotifyOnFailure bool                  `json:"notifyOnFailure"`
}

type SearchResults struct {
	Backups    []Backup   `json:"backups"`
	Databases  []Database `json:"databases"`
	Schedules  []Schedule `json:"schedules"`
	Users      []User     `json:"users"`
	TotalCount int        `json:"totalCount"`
}

type StorageProviderPayload struct {
	StorageProvider *StorageProvider `json:"storageProvider,omitempty"`
	Errors          []Error          `json:"errors,omitempty"`
}

type StorageUsageItem struct {
	Label      string          `json:"label"`
	Size       scalar.ByteSize `json:"size"`
	Count      int             `json:"count"`
	Percentage float64         `json:"percentage"`
}

type Subscription struct {
}

type Team struct {
	ID          string          `json:"id"`
	Name        string          `json:"name"`
	Description *string         `json:"description,omitempty"`
	Members     []TeamMember    `json:"members"`
	Databases   []Database      `json:"databases"`
	CreatedAt   scalar.DateTime `json:"createdAt"`
	UpdatedAt   scalar.DateTime `json:"updatedAt"`
}

type TeamMember struct {
	User     *User           `json:"user"`
	Role     TeamRole        `json:"role"`
	JoinedAt scalar.DateTime `json:"joinedAt"`
}

type TeamPayload struct {
	Team   *Team   `json:"team,omitempty"`
	Errors []Error `json:"errors,omitempty"`
}

type TestConnectionInput struct {
	Type     database.DatabaseType `json:"type"`
	Host     string                `json:"host"`
	Port     int                   `json:"port"`
	Username string                `json:"username"`
	Password string                `json:"password"`
	Database *string               `json:"database,omitempty"`
	SslMode  *SSLMode              `json:"sslMode,omitempty"`
}

type TimeRangeInput struct {
	From scalar.DateTime `json:"from"`
	To   scalar.DateTime `json:"to"`
}

type TrendDataPoint struct {
	Timestamp scalar.DateTime `json:"timestamp"`
	Value     float64         `json:"value"`
}

type UpdatePreferencesInput struct {
	Theme         *string                       `json:"theme,omitempty"`
	Language      *string                       `json:"language,omitempty"`
	Timezone      *string                       `json:"timezone,omitempty"`
	Notifications *NotificationPreferencesInput `json:"notifications,omitempty"`
}

type UpdateProfileInput struct {
	Name   *string `json:"name,omitempty"`
	Avatar *string `json:"avatar,omitempty"`
}

type UpdateRetentionPolicyInput struct {
	Name        *string `json:"name,omitempty"`
	KeepLast    *int    `json:"keepLast,omitempty"`
	KeepDaily   *int    `json:"keepDaily,omitempty"`
	KeepWeekly  *int    `json:"keepWeekly,omitempty"`
	KeepMonthly *int    `json:"keepMonthly,omitempty"`
	KeepYearly  *int    `json:"keepYearly,omitempty"`
	MinBackups  *int    `json:"minBackups,omitempty"`
	MaxBackups  *int    `json:"maxBackups,omitempty"`
}

type UpdateStorageProviderInput struct {
	Name      *string     `json:"name,omitempty"`
	Config    scalar.JSON `json:"config,omitempty"`
	IsDefault *bool       `json:"isDefault,omitempty"`
}

type UpdateTeamInput struct {
	Name        *string `json:"name,omitempty"`
	Description *string `json:"description,omitempty"`
}

type UserConnection struct {
	Edges      []UserEdge `json:"edges"`
	PageInfo   *PageInfo  `json:"pageInfo"`
	TotalCount int        `json:"totalCount"`
}

type UserEdge struct {
	Node   *User  `json:"node"`
	Cursor string `json:"cursor"`
}

type UserPayload struct {
	User   *User   `json:"user,omitempty"`
	Errors []Error `json:"errors,omitempty"`
}

type UserPreferences struct {
	Theme         string                   `json:"theme"`
	Language      string                   `json:"language"`
	Timezone      string                   `json:"timezone"`
	Notifications *NotificationPreferences `json:"notifications"`
}

type AuditAction string

const (
	AuditActionCreate  AuditAction = "CREATE"
	AuditActionUpdate  AuditAction = "UPDATE"
	AuditActionDelete  AuditAction = "DELETE"
	AuditActionRestore AuditAction = "RESTORE"
	AuditActionBackup  AuditAction = "BACKUP"
	AuditActionLogin   AuditAction = "LOGIN"
	AuditActionLogout  AuditAction = "LOGOUT"
)

var AllAuditAction = []AuditAction{
	AuditActionCreate,
	AuditActionUpdate,
	AuditActionDelete,
	AuditActionRestore,
	AuditActionBackup,
	AuditActionLogin,
	AuditActionLogout,
}

func (e AuditAction) IsValid() bool {
	switch e {
	case AuditActionCreate, AuditActionUpdate, AuditActionDelete, AuditActionRestore, AuditActionBackup, AuditActionLogin, AuditActionLogout:
		return true
	}
	return false
}

func (e AuditAction) String() string {
	return string(e)
}

func (e *AuditAction) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = AuditAction(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid AuditAction", str)
	}
	return nil
}

func (e AuditAction) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *AuditAction) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e AuditAction) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type BackupSortField string

const (
	BackupSortFieldStartTime BackupSortField = "START_TIME"
	BackupSortFieldSize      BackupSortField = "SIZE"
	BackupSortFieldDuration  BackupSortField = "DURATION"
	BackupSortFieldName      BackupSortField = "NAME"
	BackupSortFieldStatus    BackupSortField = "STATUS"
)

var AllBackupSortField = []BackupSortField{
	BackupSortFieldStartTime,
	BackupSortFieldSize,
	BackupSortFieldDuration,
	BackupSortFieldName,
	BackupSortFieldStatus,
}

func (e BackupSortField) IsValid() bool {
	switch e {
	case BackupSortFieldStartTime, BackupSortFieldSize, BackupSortFieldDuration, BackupSortFieldName, BackupSortFieldStatus:
		return true
	}
	return false
}

func (e BackupSortField) String() string {
	return string(e)
}

func (e *BackupSortField) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = BackupSortField(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid BackupSortField", str)
	}
	return nil
}

func (e BackupSortField) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *BackupSortField) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e BackupSortField) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type BackupType string

const (
	BackupTypeFull         BackupType = "FULL"
	BackupTypeIncremental  BackupType = "INCREMENTAL"
	BackupTypeDifferential BackupType = "DIFFERENTIAL"
	BackupTypeSnapshot     BackupType = "SNAPSHOT"
	BackupTypeContinuous   BackupType = "CONTINUOUS"
)

var AllBackupType = []BackupType{
	BackupTypeFull,
	BackupTypeIncremental,
	BackupTypeDifferential,
	BackupTypeSnapshot,
	BackupTypeContinuous,
}

func (e BackupType) IsValid() bool {
	switch e {
	case BackupTypeFull, BackupTypeIncremental, BackupTypeDifferential, BackupTypeSnapshot, BackupTypeContinuous:
		return true
	}
	return false
}

func (e BackupType) String() string {
	return string(e)
}

func (e *BackupType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = BackupType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid BackupType", str)
	}
	return nil
}

func (e BackupType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *BackupType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e BackupType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type CacheControlScope string

const (
	CacheControlScopePublic  CacheControlScope = "PUBLIC"
	CacheControlScopePrivate CacheControlScope = "PRIVATE"
)

var AllCacheControlScope = []CacheControlScope{
	CacheControlScopePublic,
	CacheControlScopePrivate,
}

func (e CacheControlScope) IsValid() bool {
	switch e {
	case CacheControlScopePublic, CacheControlScopePrivate:
		return true
	}
	return false
}

func (e CacheControlScope) String() string {
	return string(e)
}

func (e *CacheControlScope) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = CacheControlScope(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid CacheControlScope", str)
	}
	return nil
}

func (e CacheControlScope) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *CacheControlScope) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e CacheControlScope) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type MetricType string

const (
	MetricTypeCPUUsage     MetricType = "CPU_USAGE"
	MetricTypeMemoryUsage  MetricType = "MEMORY_USAGE"
	MetricTypeDiskUsage    MetricType = "DISK_USAGE"
	MetricTypeNetworkIo    MetricType = "NETWORK_IO"
	MetricTypeBackupCount  MetricType = "BACKUP_COUNT"
	MetricTypeBackupSize   MetricType = "BACKUP_SIZE"
	MetricTypeRestoreCount MetricType = "RESTORE_COUNT"
	MetricTypeErrorRate    MetricType = "ERROR_RATE"
	MetricTypeSuccessRate  MetricType = "SUCCESS_RATE"
)

var AllMetricType = []MetricType{
	MetricTypeCPUUsage,
	MetricTypeMemoryUsage,
	MetricTypeDiskUsage,
	MetricTypeNetworkIo,
	MetricTypeBackupCount,
	MetricTypeBackupSize,
	MetricTypeRestoreCount,
	MetricTypeErrorRate,
	MetricTypeSuccessRate,
}

func (e MetricType) IsValid() bool {
	switch e {
	case MetricTypeCPUUsage, MetricTypeMemoryUsage, MetricTypeDiskUsage, MetricTypeNetworkIo, MetricTypeBackupCount, MetricTypeBackupSize, MetricTypeRestoreCount, MetricTypeErrorRate, MetricTypeSuccessRate:
		return true
	}
	return false
}

func (e MetricType) String() string {
	return string(e)
}

func (e *MetricType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = MetricType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid MetricType", str)
	}
	return nil
}

func (e MetricType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *MetricType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e MetricType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type RestoreSortField string

const (
	RestoreSortFieldStartTime RestoreSortField = "START_TIME"
	RestoreSortFieldProgress  RestoreSortField = "PROGRESS"
	RestoreSortFieldStatus    RestoreSortField = "STATUS"
)

var AllRestoreSortField = []RestoreSortField{
	RestoreSortFieldStartTime,
	RestoreSortFieldProgress,
	RestoreSortFieldStatus,
}

func (e RestoreSortField) IsValid() bool {
	switch e {
	case RestoreSortFieldStartTime, RestoreSortFieldProgress, RestoreSortFieldStatus:
		return true
	}
	return false
}

func (e RestoreSortField) String() string {
	return string(e)
}

func (e *RestoreSortField) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = RestoreSortField(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid RestoreSortField", str)
	}
	return nil
}

func (e RestoreSortField) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *RestoreSortField) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e RestoreSortField) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type RetentionRuleType string

const (
	RetentionRuleTypeKeepLast        RetentionRuleType = "KEEP_LAST"
	RetentionRuleTypeKeepForDuration RetentionRuleType = "KEEP_FOR_DURATION"
	RetentionRuleTypeDeleteOlderThan RetentionRuleType = "DELETE_OLDER_THAN"
)

var AllRetentionRuleType = []RetentionRuleType{
	RetentionRuleTypeKeepLast,
	RetentionRuleTypeKeepForDuration,
	RetentionRuleTypeDeleteOlderThan,
}

func (e RetentionRuleType) IsValid() bool {
	switch e {
	case RetentionRuleTypeKeepLast, RetentionRuleTypeKeepForDuration, RetentionRuleTypeDeleteOlderThan:
		return true
	}
	return false
}

func (e RetentionRuleType) String() string {
	return string(e)
}

func (e *RetentionRuleType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = RetentionRuleType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid RetentionRuleType", str)
	}
	return nil
}

func (e RetentionRuleType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *RetentionRuleType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e RetentionRuleType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type SSLMode string

const (
	SSLModeDisable    SSLMode = "DISABLE"
	SSLModeRequire    SSLMode = "REQUIRE"
	SSLModeVerifyCa   SSLMode = "VERIFY_CA"
	SSLModeVerifyFull SSLMode = "VERIFY_FULL"
)

var AllSSLMode = []SSLMode{
	SSLModeDisable,
	SSLModeRequire,
	SSLModeVerifyCa,
	SSLModeVerifyFull,
}

func (e SSLMode) IsValid() bool {
	switch e {
	case SSLModeDisable, SSLModeRequire, SSLModeVerifyCa, SSLModeVerifyFull:
		return true
	}
	return false
}

func (e SSLMode) String() string {
	return string(e)
}

func (e *SSLMode) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SSLMode(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SSLMode", str)
	}
	return nil
}

func (e SSLMode) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *SSLMode) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e SSLMode) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type SortDirection string

const (
	SortDirectionAsc  SortDirection = "ASC"
	SortDirectionDesc SortDirection = "DESC"
)

var AllSortDirection = []SortDirection{
	SortDirectionAsc,
	SortDirectionDesc,
}

func (e SortDirection) IsValid() bool {
	switch e {
	case SortDirectionAsc, SortDirectionDesc:
		return true
	}
	return false
}

func (e SortDirection) String() string {
	return string(e)
}

func (e *SortDirection) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SortDirection(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SortDirection", str)
	}
	return nil
}

func (e SortDirection) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *SortDirection) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e SortDirection) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type StorageGroupBy string

const (
	StorageGroupByDatabase        StorageGroupBy = "DATABASE"
	StorageGroupByType            StorageGroupBy = "TYPE"
	StorageGroupByStatus          StorageGroupBy = "STATUS"
	StorageGroupByStorageProvider StorageGroupBy = "STORAGE_PROVIDER"
)

var AllStorageGroupBy = []StorageGroupBy{
	StorageGroupByDatabase,
	StorageGroupByType,
	StorageGroupByStatus,
	StorageGroupByStorageProvider,
}

func (e StorageGroupBy) IsValid() bool {
	switch e {
	case StorageGroupByDatabase, StorageGroupByType, StorageGroupByStatus, StorageGroupByStorageProvider:
		return true
	}
	return false
}

func (e StorageGroupBy) String() string {
	return string(e)
}

func (e *StorageGroupBy) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = StorageGroupBy(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid StorageGroupBy", str)
	}
	return nil
}

func (e StorageGroupBy) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *StorageGroupBy) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e StorageGroupBy) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type StorageStatus string

const (
	StorageStatusOnline   StorageStatus = "ONLINE"
	StorageStatusOffline  StorageStatus = "OFFLINE"
	StorageStatusDegraded StorageStatus = "DEGRADED"
	StorageStatusFull     StorageStatus = "FULL"
)

var AllStorageStatus = []StorageStatus{
	StorageStatusOnline,
	StorageStatusOffline,
	StorageStatusDegraded,
	StorageStatusFull,
}

func (e StorageStatus) IsValid() bool {
	switch e {
	case StorageStatusOnline, StorageStatusOffline, StorageStatusDegraded, StorageStatusFull:
		return true
	}
	return false
}

func (e StorageStatus) String() string {
	return string(e)
}

func (e *StorageStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = StorageStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid StorageStatus", str)
	}
	return nil
}

func (e StorageStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *StorageStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e StorageStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type TeamRole string

const (
	TeamRoleOwner  TeamRole = "OWNER"
	TeamRoleAdmin  TeamRole = "ADMIN"
	TeamRoleMember TeamRole = "MEMBER"
	TeamRoleViewer TeamRole = "VIEWER"
)

var AllTeamRole = []TeamRole{
	TeamRoleOwner,
	TeamRoleAdmin,
	TeamRoleMember,
	TeamRoleViewer,
}

func (e TeamRole) IsValid() bool {
	switch e {
	case TeamRoleOwner, TeamRoleAdmin, TeamRoleMember, TeamRoleViewer:
		return true
	}
	return false
}

func (e TeamRole) String() string {
	return string(e)
}

func (e *TeamRole) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = TeamRole(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid TeamRole", str)
	}
	return nil
}

func (e TeamRole) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *TeamRole) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e TeamRole) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type TimeUnit string

const (
	TimeUnitHours  TimeUnit = "HOURS"
	TimeUnitDays   TimeUnit = "DAYS"
	TimeUnitWeeks  TimeUnit = "WEEKS"
	TimeUnitMonths TimeUnit = "MONTHS"
	TimeUnitYears  TimeUnit = "YEARS"
)

var AllTimeUnit = []TimeUnit{
	TimeUnitHours,
	TimeUnitDays,
	TimeUnitWeeks,
	TimeUnitMonths,
	TimeUnitYears,
}

func (e TimeUnit) IsValid() bool {
	switch e {
	case TimeUnitHours, TimeUnitDays, TimeUnitWeeks, TimeUnitMonths, TimeUnitYears:
		return true
	}
	return false
}

func (e TimeUnit) String() string {
	return string(e)
}

func (e *TimeUnit) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = TimeUnit(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid TimeUnit", str)
	}
	return nil
}

func (e TimeUnit) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *TimeUnit) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e TimeUnit) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
