apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: db-backup-gateway
  namespace: db-backup
  labels:
    app.kubernetes.io/name: db-backup
    app.kubernetes.io/component: service-mesh
spec:
  selector:
    istio: ingressgateway

  servers:
    # HTTPS
    - port:
        number: 443
        name: https
        protocol: HTTPS
      tls:
        mode: SIMPLE
        credentialName: db-backup-tls-credential
      hosts:
        - api.backup.example.com

    # HTTP redirect to HTTPS
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - api.backup.example.com
      tls:
        httpsRedirect: true
